"""empty message

Revision ID: 48ccbb11c6a6
Revises: 
Create Date: 2024-05-31 19:31:02.606083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ccbb11c6a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker', sa.String(length=200), nullable=False),
    sa.Column('blocked_user', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_id', sa.String(length=200), nullable=False),
    sa.Column('pw', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=False),
    sa.Column('insta', sa.String(length=200), nullable=False),
    sa.Column('kakao', sa.String(length=200), nullable=False),
    sa.Column('menu', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('talking', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('blocked_cnt', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('std_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blocked_list')
    # ### end Alembic commands ###
